CREATE SCHEMA EXTRACTION;

CREATE SCHEMA INTEGRATION;

CREATE SCHEMA DISTRIBUTION;

CREATE OR REPLACE TABLE EXTRACTION.EXT_CUSTOMER (
    customer_id INT NOT NULL,
    customer_name STRING,
    customer_address STRING,
    DT_INSERT TIMESTAMP
);


SELECT * FROM EXTRACTION.EXT_CUSTOMER;
TRUNCATE TABLE EXTRACTION.EXT_CUSTOMER;

CREATE OR REPLACE TABLE DISTRIBUTION.DST_CUSTOMER (
    customer_id INT PRIMARY KEY,
    customer_name STRING,
    customer_address STRING,
    dt_insert timestamp
);

SELECT * FROM DISTRIBUTION.DST_CUSTOMER A;
TRUNCATE TABLE  DISTRIBUTION.DST_CUSTOMER;
--------------------------------SCD1

MERGE INTO DISTRIBUTION.DST_CUSTOMER A
USING (SELECT * FROM EXTRACTION.EXT_CUSTOMER
WHERE DT_INSERT = (SELECT MAX(DT_INSERT) FROM  EXTRACTION.EXT_CUSTOMER))B
ON A.customer_id = B.customer_id
WHEN MATCHED THEN 
UPDATE SET
A.customer_name = B.customer_name,
A.customer_address = B.customer_address,
A.DT_INSERT = CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN
INSERT (customer_id,customer_name, customer_address, DT_INSERT)
VALUES (B.customer_id,B.customer_name, B.customer_address, CURRENT_TIMESTAMP);




