CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE
URL = 's3://snowflaketestingbuckets3'
credentials=(aws_key_id='******' aws_secret_key='e6mNpF4Z/QTmXQjeWgjfAQn+i1k/xuv4yBfqzXfk');

LIST @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_AS6;

CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.AWS_FILEFORMAT_JSON
TYPE = 'JSON';


CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.JSON_RAW(
RAW VARIANT );


COPY INTO OUR_FIRST_DB.PUBLIC.JSON_RAW
FROM @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE
FILE_FORMAT = MANAGE_DB.FILE_FORMATS.AWS_FILEFORMAT_JSON
FILES = ('HR_data.json');

SELECT * FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;
