CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_AS6
URL = 's3://snowflake-assignments-mc/unstructureddata/' ;

LIST @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_AS6;

CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.AWS_FILEFORMAT_AS6
TYPE = 'JSON';


CREATE OR REPLACE TABLE EXERCISE_DB.PUBLIC.JSON_RAW(
RAW VARIANT );


COPY INTO EXERCISE_DB.PUBLIC.JSON_RAW
FROM @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_AS6
FILE_FORMAT = MANAGE_DB.FILE_FORMATS.AWS_FILEFORMAT_AS6;

SELECT * FROM EXERCISE_DB.PUBLIC.JSON_RAW;
