TRUNCATE TABLE EXERCISE_DB.PUBLIC.CUSTOMERS;
SELECT * FROM EXERCISE_DB.PUBLIC.CUSTOMERS;

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_AS4
URL = 's3://snowflake-assignments-mc/copyoptions/example1';

LIST @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_AS4;

COPY INTO EXERCISE_DB.PUBLIC.CUSTOMERS
FROM @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_AS4
FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER = ',' SKIP_HEADER = 1)
VALIDATION_MODE = RETURN_ERRORS;

COPY INTO EXERCISE_DB.PUBLIC.CUSTOMERS
FROM @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_AS4
FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER = ',' SKIP_HEADER = 1)
--VALIDATION_MODE = RETURN_ERRORS
ON_ERROR = 'CONTINUE';
