CREATE OR REPLACE TABLE COPY_DB.PUBLIC.EMPLOYEE(
CUSTOMER_ID INT,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
EMAIL VARCHAR(50),
AGE INT,
DEPARTMENT VARCHAR(50)
);

SELECT * FROM  COPY_DB.PUBLIC.EMPLOYEE;

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_AS5
URL = 's3://snowflake-assignments-mc/copyoptions/example2';

LIST @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_AS5;

CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.AWS_FILEFORMAT_AS5
TYPE = 'CSV'
FIELD_DELIMITER = ',',
SKIP_HEADER = 1;

DESC FILE FORMAT MANAGE_DB.FILE_FORMATS.AWS_FILEFORMAT_AS5;

COPY INTO COPY_DB.PUBLIC.EMPLOYEE
FROM @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_AS5
FILE_FORMAT = MANAGE_DB.FILE_FORMATS.AWS_FILEFORMAT_AS5
VALIDATION_MODE = RETURN_ERRORS;


COPY INTO COPY_DB.PUBLIC.EMPLOYEE
FROM @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_AS5
FILE_FORMAT = MANAGE_DB.FILE_FORMATS.AWS_FILEFORMAT_AS5
TRUNCATECOLUMNS = TRUE
VALIDATION_MODE = RETURN_ERRORS;


COPY INTO COPY_DB.PUBLIC.EMPLOYEE
FROM @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_AS5
FILE_FORMAT = MANAGE_DB.FILE_FORMATS.AWS_FILEFORMAT_AS5
TRUNCATECOLUMNS = TRUE;


