TRUNCATE TABLE EXERCISE_DB.PUBLIC.CUSTOMERS;
SELECT * FROM EXERCISE_DB.PUBLIC.CUSTOMERS;

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_AS3
URL = 's3://snowflake-assignments-mc/fileformat/' ;

DESC STAGE MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_AS3;

LIST @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_AS3;

CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.AWS_FILEFORMAT_AS3
TYPE = 'CSV',
FIELD_DELIMITER = '|'
SKIP_HEADER = 1;

DESC FILE FORMAT MANAGE_DB.FILE_FORMATS.AWS_FILEFORMAT_AS3;

COPY INTO EXERCISE_DB.PUBLIC.CUSTOMERS
FROM @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE_AS3
FILE_FORMAT = (FORMAT_NAME = MANAGE_DB.FILE_FORMATS.AWS_FILEFORMAT_AS3)
ON_ERROR = 'CONTINUE';
